"use client";
import { FormEvent, useEffect, useState } from "react";

const services = [["01","Tree removal","Safely clear problem trees, fallen limbs, and the mess they leave behind.","./work/fallen-tree.png"],["02","Trimming & pruning","Thoughtful cuts for safer limbs, healthier canopies, and better-looking trees.","./work/arborist-at-work.png"],["03","Brush & lot clearing","Turn dense overgrowth into usable, ready-for-what's-next space.","./work/tree-chipper.png"]];
const reviews = [["Vicki Ngo","vicki-ngo","Super helpful throughout the whole process and made sure we felt comfortable."],["Matthew Marquis","matthew-marquis","Extremely professional and listened to my needs. 10/10 would use again."],["Marc Gomez","marc-gomez","Big oak removed and stump ground — I was not let down."],["Nancy Ford","nancy-ford","Very nice crew that removed invasive trees and cleaned up really well."],["David Akin","david-akin","Fast work, attention to detail, and all remnants removed."],["Stephanie Marquis","stephanie-marquis","Professional advice and excellent service. Would use again."],["Dee Cee","dee-cee","Quality work and professionalism."],["Jetblacklotus","jetblacklotus","Responsive, punctual, professional, and a great value."],["Angela Pierce","angela-pierce","Responsive, quality service, and professionalism."]];
export default function Home(){const [done,setDone]=useState(false);const [menu,setMenu]=useState(false);useEffect(()=>{const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("in");o.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll(".reveal").forEach(n=>o.observe(n));return()=>o.disconnect()},[]);function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setDone(true)}return <main>
<header className="island"><a className="brand" href="#top"><i>SA</i><b>Tree &amp; Brush</b></a><nav className={menu?"open":""}><a href="#services" onClick={()=>setMenu(false)}>Services</a><a href="#reviews" onClick={()=>setMenu(false)}>Reviews</a><a href="#area" onClick={()=>setMenu(false)}>Area</a></nav><a className="phone-link" href="tel:+12109340335"><small>Call for service</small><b>(210) 934-0335</b></a><a className="quote-link" href="#quote">Free quote <span>↗</span></a><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Menu"><i/><i/></button></header>
<section id="top" className="hero"><div className="hero-copy"><p className="eyebrow">San Antonio tree service</p><h1>Tree trimming,<br/><em>removal &amp; cleanup.</em></h1><p>San Antonio Tree &amp; Brush Removal handles trimming, tree removal, brush clearing, stump grinding, and cleanup for local homes and properties.</p><div className="actions"><a className="pill dark" href="#quote">Request a free quote <b>→</b></a><a className="call-hero" href="tel:+12109340335"><small>Call now</small><strong>(210) 934-0335</strong></a></div><div className="tags"><span>San Antonio service area</span><span>5.0 stars · 10 reviews</span><span>Free project quotes</span></div></div><div className="hero-art"><div className="bezel"><img src="./work/arborist-at-work.png" alt="Arborist safely working in a tree"/></div><small>Tree trimming<br/>Removal · Cleanup</small><label>Local crew<br/>San Antonio, TX</label></div></section>
<section className="intro reveal"><div className="intro-copy"><p className="eyebrow">Tree service made clear</p><h2>Practical help<br/>for your <em>property.</em></h2><p>Need an overgrown tree trimmed, a dead tree removed, or a yard cleaned up after the work? Tell us what is happening and we&rsquo;ll help you plan the right next step.</p></div><div className="intro-trust"><article><strong>5.0</strong><span>Google rating</span></article><article><strong>10</strong><span>Customer reviews</span></article><article><strong>SA</strong><span>Local service area</span></article><a href="tel:+12109340335">Call (210) 934-0335 <b>↗</b></a></div></section>
<section className="services" id="services">{services.map(([num,title,text,img])=><article className="service reveal" key={title}><div className="service-photo"><img src={img} alt=""/></div><div><span>{num}</span><h3>{title}</h3><p>{text}</p><a href="#quote">Request service <b>↗</b></a></div></article>)}</section>
<section className="method reveal"><div><p className="eyebrow">How it works</p><h2>Simple from<br/>the <em>first call.</em></h2></div><ol><li><b>01</b><h3>Tell us the situation</h3><p>A few notes about the property or issue is enough to get started.</p></li><li><b>02</b><h3>Get a clear approach</h3><p>We talk through what needs to happen and how we&rsquo;ll handle it.</p></li><li><b>03</b><h3>Enjoy the reset</h3><p>The space is clean, clear, and ready to use.</p></li></ol></section>
<section className="proof reveal" id="reviews"><div><p className="eyebrow">Customer notes</p><h2>Good work<br/>leaves a <em>mark.</em></h2><p className="stars">★★★★★</p><p>Real Google reviews from San Antonio homeowners.</p></div><div className="review-grid">{reviews.map(([name,img,quote])=><article key={name}><header><img src={`./reviews/${img}.png`} alt={`${name} profile`}/><span><b>{name}</b><i>★★★★★</i></span></header><p>“{quote}”</p></article>)}</div></section>
<section id="area" className="area reveal"><div><p className="eyebrow">Serving San Antonio</p><h2>Close to<br/><em>the work.</em></h2><p>Helping local homes, lots, and businesses create safer, more usable outdoor space.</p><a className="pill dark" href="https://www.google.com/maps/place/San+Antonio+Tree+and+Brush+Removal/@29.5202864,-98.481919,13z" target="_blank">Open Google Maps <b>↗</b></a></div><div className="map"><iframe title="San Antonio Tree and Brush Removal" src="https://www.google.com/maps?q=San%20Antonio%20Tree%20and%20Brush%20Removal%2C%20San%20Antonio%2C%20TX&output=embed" loading="lazy"/></div></section>
<section id="quote" className="contact"><div><p className="eyebrow">No-pressure start</p><h2>What needs<br/><em>clearing?</em></h2><p>Send the broad strokes. This is a demo, so nothing is delivered to the business.</p></div>{done?<div className="success"><b>✓</b><h3>Demo request received.</h3><p>Your information was not sent anywhere.</p><button onClick={()=>setDone(false)}>Start another request</button></div>:<form onSubmit={submit}><label>Name<input required placeholder="First and last name"/></label><label>Phone or email<input required placeholder="Best way to reach you"/></label><label>Service<select required defaultValue=""><option disabled value="">Select what you need</option><option>Tree removal</option><option>Trimming & pruning</option><option>Brush & lot clearing</option><option>Stump grinding</option></select></label><label>Project notes<textarea rows={3} placeholder="Tell us what is going on"/></label><button className="pill dark">Send demo request <b>→</b></button><small>Demo only — no information is sent.</small></form>}</section><footer><a className="brand" href="#top"><i>SA</i><b>Tree &amp; Brush</b></a><span>San Antonio Tree &amp; Brush Removal</span><a href="#top">Back to top ↑</a></footer></main>}
